'use strict'

const { describe, it, afterEach } = require('node:test')
const assert = require('node:assert')

const { _canonicalIP, _isUsableIP, HOSTS_BEGIN, HOSTS_END, buildHostsOutput, GrimHost } = require('../bin/grim-host.js')

// ── _isUsableIP ───────────────────────────────────────────────────────────────

describe('_isUsableIP', () => {
  it('rejects loopback',          () => assert.equal(_isUsableIP('127.0.0.1'),  false))
  it('rejects link-local',        () => assert.equal(_isUsableIP('169.254.1.2'), false))
  it('accepts LAN',               () => assert.equal(_isUsableIP('192.168.0.1'), true))
  it('accepts private 10.x',      () => assert.equal(_isUsableIP('10.0.0.1'),  true))
  it('rejects null',              () => assert.equal(_isUsableIP(null),         false))
  it('rejects empty string',      () => assert.equal(_isUsableIP(''),           false))
  it('rejects IPv6',              () => assert.equal(_isUsableIP('fe80::1'),    false))
  it('rejects multicast',         () => assert.equal(_isUsableIP('224.0.0.1'), false))
})

// ── _canonicalIP ──────────────────────────────────────────────────────────────

describe('_canonicalIP', () => {
  it('returns null for empty array', () => {
    assert.equal(_canonicalIP([]), null)
  })

  it('returns null when all IPs filtered', () => {
    const addrs = [
      { ip: '127.0.0.1', iface: 'lo' },
      { ip: '169.254.1.2', iface: 'eth0' },
    ]
    assert.equal(_canonicalIP(addrs), null)
  })

  it('picks lowest LAN IP when multiple exist', () => {
    const addrs = [
      { ip: '192.168.0.181', iface: 'eth0' },
      { ip: '169.254.1.2',   iface: 'eth0' },
      { ip: '127.0.0.1',     iface: 'lo' },
      { ip: '192.168.0.141', iface: 'eth1' },
    ]
    assert.equal(_canonicalIP(addrs), '192.168.0.141')
  })

  it('returns single IP when only one exists', () => {
    const addrs = [{ ip: '192.168.0.242', iface: 'eth0' }]
    assert.equal(_canonicalIP(addrs), '192.168.0.242')
  })

  it('handles undefined input', () => {
    assert.equal(_canonicalIP(undefined), null)
  })
})

// ── Managed block idempotency ─────────────────────────────────────────────────

describe('managed block idempotency', () => {
  function applyBlock(current, newBlock) {
    const beginIdx = current.indexOf(HOSTS_BEGIN)
    const endIdx   = current.indexOf(HOSTS_END)
    // Mirror _applyHosts: trim trailing blanks from newBlock, wrap in markers
    const cleanBlock = (HOSTS_BEGIN + '\n' + newBlock.trimEnd() + '\n' + HOSTS_END).trimEnd()
    if (beginIdx !== -1 && endIdx !== -1) {
      const after = current.slice(endIdx + HOSTS_END.length)
      return current.slice(0, beginIdx) + cleanBlock + (after.startsWith('\n') ? after : '\n' + after)
    }
    const firstContent = current.search(/[^\s#]/)
    if (firstContent === -1) return current + '\n' + cleanBlock
    return current.slice(0, firstContent) + '\n' + cleanBlock + current.slice(firstContent)
  }

  it('replaces existing block in place', () => {
    const existing = `${HOSTS_BEGIN}\n192.168.0.141  blip\n${HOSTS_END}\n10.0.0.1 outside\n`
    const newBlock = '# Generated by: grim host gen-hosts\n192.168.0.202  aid\n'
    const result   = applyBlock(existing, newBlock)
    assert.ok(result.includes('192.168.0.202  aid'))
    assert.ok(!result.includes('192.168.0.141  blip'))
    assert.ok(result.includes('10.0.0.1 outside'))
  })

  it('is idempotent: second apply produces same output', () => {
    // Simulate first-run result (block inserted before first content line)
    const afterFirst = HOSTS_BEGIN + '\n# Generated by: grim host gen-hosts\n192.168.0.141  blip\n' + HOSTS_END + '\n127.0.0.1 localhost\n10.0.0.1 outside\n'
    // newBlock mirrors what genHosts outputs on second run — same content
    const newBlock   = '# Generated by: grim host gen-hosts\n192.168.0.141  blip\n'
    const r2 = applyBlock(afterFirst, newBlock)
    const strip = s => s.replace(/\n+$/, '')
    assert.equal(strip(afterFirst), strip(r2), 'second apply should produce same content')
  })

  it('inserts block before first content line when none exists', () => {
    const existing = '# comment\n127.0.0.1 localhost\n10.0.0.1 outside\n'
    const newBlock = '# Generated by: grim host gen-hosts\n192.168.0.202  aid\n'
    const result   = applyBlock(existing, newBlock)
    // Block inserts before first non-comment line (127.0.0.1)
    assert.ok(result.includes('127.0.0.1 localhost'))
    assert.ok(result.includes('10.0.0.1 outside'))
    assert.ok(result.includes(HOSTS_BEGIN))
    assert.ok(result.includes('192.168.0.202  aid'))
  })

  it('preserves lines outside markers', () => {
    const existing = '127.0.0.1 localhost\n# mid\n10.0.0.1 outside\n'
    const newBlock = '# Generated by: grim host gen-hosts\n192.168.0.202  aid\n'
    const result   = applyBlock(existing, newBlock)
    assert.ok(result.includes('127.0.0.1 localhost'))
    assert.ok(result.includes('# mid'))
    assert.ok(result.includes('10.0.0.1 outside'))
  })
})

// ── buildHostsOutput (shared by CLI local mode + server /api/hosts) ─────────────

describe('buildHostsOutput', () => {
  const hosts = [
    { name: 'chonko', network: { addresses: [{ ip: '192.168.0.242', iface: 'eth0' }, { ip: '169.254.1.2', iface: 'eth0' }] } },
    { name: 'aid',    network: { addresses: [{ ip: '192.168.0.202', iface: 'eth0' }] } },
    { name: 'ghost',  network: { addresses: [{ ip: '127.0.0.1', iface: 'lo' }] } },
  ]

  it('emits one canonical LAN IP per host, sorted by name', () => {
    const out = buildHostsOutput(hosts)
    const lines = out.split('\n').filter(l => l && !l.startsWith('#'))
    // sorted: aid, chonko (ghost has no usable IP → comment, not a line)
    assert.equal(lines[0], '192.168.0.202         aid'.replace(/ +/, m => ' '.repeat(20 - '192.168.0.202'.length + 1)))
    assert.ok(out.includes('192.168.0.202'))
    assert.ok(out.includes('aid'))
    assert.ok(out.indexOf('aid') < out.indexOf('chonko'))  // sorted
  })

  it('drops link-local, keeps the LAN IP', () => {
    const out = buildHostsOutput(hosts)
    assert.ok(!out.includes('169.254.1.2'))
    assert.ok(out.includes('192.168.0.242'))
  })

  it('comments a host with no usable IP instead of emitting a broken line', () => {
    const out = buildHostsOutput(hosts)
    assert.ok(out.includes('# ghost: no usable IP recorded'))
    assert.ok(!/\S+\s+ghost$/m.test(out.replace('# ghost', '')))  // no "IP ghost" line
  })

  it('includes the generated-by header', () => {
    assert.ok(buildHostsOutput([]).includes('# Generated by: grim host gen-hosts'))
  })
})

// ── uid-0 guard ───────────────────────────────────────────────────────────────

describe('genHosts uid-0 guard', () => {
  it('refuses to run when uid is 0 (no SUDO_USER)', async () => {
    const h = new GrimHost()
    const origGetuid = process.getuid
    process.getuid = () => 0
    const origExit = process.exit
    const origStderr = process.stderr.write
    let exitCode = null
    let stderr = ''
    process.exit = (code) => { exitCode = code; throw Object.assign(new Error('exit ' + code), { code }) }
    process.stderr.write = (chunk) => { stderr += chunk; return origStderr.call(process.stderr, chunk) }
    try {
      await h.genHosts({ apply: true })
      assert.fail('should have thrown')
    } catch (e) {
      assert.equal(e.message, 'exit 1')
      assert.equal(exitCode, 1)
      assert.ok(stderr.includes("Don't run grim as root"), `expected root warning in stderr, got: ${stderr}`)
    } finally {
      process.getuid = origGetuid
      process.exit = origExit
      process.stderr.write = origStderr
    }
  })

  it('refuses to run when uid is 0 (with SUDO_USER set)', async () => {
    const h = new GrimHost()
    const origGetuid = process.getuid
    process.getuid = () => 0
    const origEnv = process.env.SUDO_USER
    process.env.SUDO_USER = 'vgvm'
    const origExit = process.exit
    const origStderr = process.stderr.write
    let exitCode = null
    let stderr = ''
    process.exit = (code) => { exitCode = code; throw Object.assign(new Error('exit ' + code), { code }) }
    process.stderr.write = (chunk) => { stderr += chunk; return origStderr.call(process.stderr, chunk) }
    try {
      await h.genHosts({ apply: true })
      assert.fail('should have thrown')
    } catch (e) {
      assert.equal(e.message, 'exit 1')
      assert.equal(exitCode, 1)
      assert.ok(stderr.includes("Don't run grim under sudo"), `expected sudo warning in stderr, got: ${stderr}`)
      assert.ok(stderr.includes('vgvm'), `expected SUDO_USER in message, got: ${stderr}`)
    } finally {
      process.getuid = origGetuid
      process.exit = origExit
      process.stderr.write = origStderr
      if (origEnv === undefined) delete process.env.SUDO_USER
      else process.env.SUDO_USER = origEnv
    }
  })
})

// ── list remote mode ──────────────────────────────────────────────────────────

describe('list remote mode', () => {
  const { config } = require('../lib/env')
  const origRoot = config.root
  const origHost = config.host

  afterEach(() => {
    config.root = origRoot
    config.host = origHost
  })

  it('_fetchHosts uses local KB when config.root is set', async () => {
    config.root = '/home/vgvm/data/grimoire-kb'
    config.host = null
    const h = new GrimHost()
    const hosts = await h._fetchHosts()
    assert.ok(Array.isArray(hosts))
    assert.ok(hosts.length > 0)
    assert.equal(hosts[0].tags.includes('hardware/inventory'), true)
  })

  it('_fetchHosts falls back to remote when config.root is null', async () => {
    config.root = null
    config.host = 'http://aid:3663'
    const h = new GrimHost()
    const hosts = await h._fetchHosts()
    assert.ok(Array.isArray(hosts))
    assert.ok(hosts.length > 0)
    assert.equal(hosts[0].name, 'aid')
  })

  it('_fetchHosts throws NO_SOURCE when neither root nor host available', async () => {
    config.root = null
    config.host = null
    const h = new GrimHost()
    try {
      await h._fetchHosts()
      assert.fail('should have thrown')
    } catch (e) {
      assert.equal(e.code, 'NO_SOURCE')
      assert.ok(e.message.includes('No local KB and no grimoire server resolved'))
    }
  })

  it('_fetchHosts throws REMOTE_FAIL on unreachable server', async () => {
    config.root = null
    config.host = 'http://127.0.0.1:1/nonexistent'
    const h = new GrimHost()
    try {
      await h._fetchHosts()
      assert.fail('should have thrown')
    } catch (e) {
      assert.equal(e.code, 'REMOTE_FAIL')
      assert.ok(e.message.includes('Could not fetch host inventory'))
    }
  })

  it('_renderHostList prints nothing for empty array', async () => {
    const h = new GrimHost()
    const origStdout = process.stdout.write
    let out = ''
    process.stdout.write = (chunk) => { out += chunk; return true }
    try {
      h._renderHostList([])
      assert.ok(out.includes('No registered hosts'))
    } finally {
      process.stdout.write = origStdout
    }
  })

  it('_renderHostList formats hosts with IP and description', async () => {
    const h = new GrimHost()
    const origStdout = process.stdout.write
    let out = ''
    process.stdout.write = (chunk) => { out += chunk; return true }
    try {
      h._renderHostList([
        { name: 'aid', network: { addresses: [{ ip: '192.168.0.202' }] }, description: 'test host' },
      ])
      assert.ok(out.includes('aid'))
      assert.ok(out.includes('192.168.0.202'))
      assert.ok(out.includes('test host'))
    } finally {
      process.stdout.write = origStdout
    }
  })

  it('list() exits 1 with actionable message when no source', async () => {
    config.root = null
    config.host = null
    const h = new GrimHost()
    const origExit = process.exit
    let exitCode = null
    process.exit = (code) => { exitCode = code; throw Object.assign(new Error('exit ' + code), { code }) }
    try {
      await h.list()
      assert.fail('should have thrown')
    } catch (e) {
      assert.equal(e.message, 'exit 1')
      assert.equal(exitCode, 1)
    } finally {
      process.exit = origExit
    }
  })
})
